#ifndef __DEFINITIONS_H__
#define __DEFINITIONS_H__

#define DISPLAY_TIME_SPLASH_SCENE 2
#define TRANSITION_TIME 0.5
#define OBSTACLE_SPAWN_FREQUENCY 0.005

#define OBSTACLE_GAP 4
#define UPPER_SCREEN_OBSTACLE_THRESHOLD 0.35
#define LOWER_SCREEN_OBSTACLE_THRESHOLD 0.65

#define OBSTACLE_MOVEMENT_SPEED 0.01

#define FABBY_COLLISION_BITMASK 0x000001
#define OBSTACLE_COLLISION_BITMASK 0x000002
#define POINT_COLLISION_BITMASK 0x000003

#define FABBY_FALLING_SPEED 0.0025
#define FABBY_FLYING_SPEED 0.00375
#define FABBY_FLY_DURATION 0.25

#define SCORE_FONT_SIZE 0.1

#endif // __DEFINITIONS_H__
